run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
  gofmt:
    simplify: true

issues:
  exclude-rules:
    # Ignorer les erreurs non vérifiées dans les tests
    - path: _test\.go
      linters:
        - errcheck
    # Ignorer les assignations inutilisées dans les Exec SQL
    - linters:
        - ineffassign
      source: "db\\.Exec"
